# Generated by Django 4.2.9 on 2024-01-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_new_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Contact',
        ),
    ]
